// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVaEhEJq9MT_OX1UzyYiy_IV9hExa3J60',
    appId: '1:943759980054:web:bec0bbfd5287140f7e2737',
    messagingSenderId: '943759980054',
    projectId: 'celebritysystemsfcm',
    authDomain: 'celebritysystemsfcm.firebaseapp.com',
    storageBucket: 'celebritysystemsfcm.firebasestorage.app',
    measurementId: 'G-MVYFEMQHL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC-enmmKqWSDiWTPAcJbfQkR77gacHj_k',
    appId: '1:943759980054:android:91be1294a1f11f747e2737',
    messagingSenderId: '943759980054',
    projectId: 'celebritysystemsfcm',
    storageBucket: 'celebritysystemsfcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1znzc7qVMgm5OB82gak4sGQz0wBO1nrw',
    appId: '1:943759980054:ios:5342230bd1c200517e2737',
    messagingSenderId: '943759980054',
    projectId: 'celebritysystemsfcm',
    storageBucket: 'celebritysystemsfcm.firebasestorage.app',
    iosBundleId: 'com.example.celebritysystemsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1znzc7qVMgm5OB82gak4sGQz0wBO1nrw',
    appId: '1:943759980054:ios:5342230bd1c200517e2737',
    messagingSenderId: '943759980054',
    projectId: 'celebritysystemsfcm',
    storageBucket: 'celebritysystemsfcm.firebasestorage.app',
    iosBundleId: 'com.example.celebritysystemsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVaEhEJq9MT_OX1UzyYiy_IV9hExa3J60',
    appId: '1:943759980054:web:294f57fce55a394c7e2737',
    messagingSenderId: '943759980054',
    projectId: 'celebritysystemsfcm',
    authDomain: 'celebritysystemsfcm.firebaseapp.com',
    storageBucket: 'celebritysystemsfcm.firebasestorage.app',
    measurementId: 'G-NYVTZ2TE14',
  );
}
